services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springuser
      POSTGRES_DB: its
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/its
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springuser
    depends_on:
      - db
    volumes:
      # テンプレートファイルをリアルタイム同期
      - ./src/main/resources/templates:/app/src/main/resources/templates
      # 静的ファイル（CSS、JS、画像）をリアルタイム同期
      - ./src/main/resources/static:/app/src/main/resources/static
      # アプリケーション設定ファイルもリアルタイム同期
      - ./src/main/resources/application.properties:/app/src/main/resources/application.properties
      # Javaソースファイルをリアルタイム同期
      - ./src/main/java:/app/src/main/java
