version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springuser
      POSTGRES_DB: its
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/its
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springuser
    depends_on:
      - db
